[phases.build]
cmds = [
  "composer install --no-interaction --optimize-autoloader --no-scripts",
  "npm run build"
]

[phases.start]
cmd = "php artisan migrate --force && php artisan config:cache && vendor/bin/heroku-php-apache2 public/"
